import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 * Class to output text results to a window
 */
public class ResultWindow extends JFrame {
	private static final long serialVersionUID = 1L;
	private JScrollPane scroller;
	private JTextArea output;

	/**
	 * Constructor
	 */
	public ResultWindow() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		scroller = new JScrollPane();
		output = new JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		output.setColumns(20);
		output.setRows(5);
		scroller.setViewportView(output);

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGroup(
						layout.createSequentialGroup().addComponent(scroller,
								GroupLayout.PREFERRED_SIZE, 800,
								GroupLayout.PREFERRED_SIZE))));

		layout.setVerticalGroup(layout.createParallelGroup(
				GroupLayout.Alignment.LEADING).addGroup(
				GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addComponent(scroller,
						GroupLayout.PREFERRED_SIZE, 400,
						GroupLayout.PREFERRED_SIZE)));

		pack();
	}

	/**
	 * Appends text to the results window
	 * 
	 * @param text - the text to output
	 */
	public void updateText(String text) {
		output.append(text + "\n");
		output.setCaretPosition(output.getDocument().getLength());
	}
}